spring.application.name=fijiimpulse

server.port=8081

#DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/fiji-impulse-1
#spring.datasource.url=jdbc:mysql://improved-energy-cheap-indicated.trycloudflare.com/index.php?route=/database/structure&db=SA
spring.datasource.username=root
spring.datasource.password=


#App setting
spring.main.banner-mode=off
#logging.level.root=info
#logging.level.root=warn
#logging.level.root=off


#DB setting
spring.jpa.hibernate.ddl-auto=update